### ISSUE TITLE
[Request] Implementation on own website

### ISSUE THREAD

**Issue by wavester** [NielsjeNL/srb2kb#1]
Hey there,

I was wondering whether it's allowed to use this code for my own website. I wanted to make a status page for my SRB2Kart servers and this looks perfect for that purpose. Figured i would first ask for permission since i didn't want to piss anyone off.

Kind regards,

Wavy

**Comment by NielsjeNL** [comment]
Hey Wavy, you're fine to host this application on your own domain. That's why we put it on GitHub; so people could do so. ;)
There's still some static links to my own personal domain in the code, I'll look at getting those replaced hopefully soon.
If anyone else would be willing to take a look at this, that would be great too.

Good luck! @wavester

**Comment by wavester** [comment]
Appreciate the quick response, dude! Best of luck to you too with this project. Think it's excellent!
